### ISSUE TITLE
{Electron}{Web} conflict with the same merge doesnt enable Merge Master Branh.

### ISSUE THREAD

**Issue by Jacob15** [standlove/percy-issues#36] opened 2019-01-22 07:01 UTC
Steps to Reproduce

1. Login to webapp.
2. Change a file in Develop branch. 
3. Change the same file in Master branch using Bitbucket
4. Refresh in Dashboard. Merge Master branch enabled for Develop branch
5. Click on Merge Master branch which is enabled.
6. In the conflict choose develop branch and then create pull request.
7. Then refresh in the dashboard.
8. Merge Master branch is enabled for develop branch. only through Bitbucket user able to proceed.

Actual Result
Merge Master is not enable in second time after pull request.

Expected Result
Merge Master should be enabled during second time.

Frequency:
5/5

Device: Laptop
OS : Windows 7 32 bit

Images
http://www.screencast.com/t/Y446CppcVe

**Comment by liuliquan** [comment] 2019-01-22 07:40
In step 8 you said: "Merge Master branch is enabled"

In Actual Result you said: "Merge Master is not enable in second time"

So is it enabled or not enabled?

In screen video, it looks it is not enabled in second time.

And this is expected behavior, because:
1. At first master is merged into develop branch 
2. Then develop branch is merged back into master through pull request
3. Now master branch is same as develop branch, so "Merge Master" button should be disabled

**Comment by Jacob15** [comment] 2019-01-22 11:13
@liuliquan Not enabled. Fine. Bit confused with Merge files to the master repo.

**Closed as completed** 2019-01-23 01:08 UTC
Labels: invalid
